title: Forest SVG Documentation
email: fbrereto@adobe.com
description: >- # this means to ignore newlines until "baseurl:"
  A site for documentation of `adobe::forest<T>` with examples written in SVG.
baseurl: "/forest-svg-docs" # the subpath of your site, e.g. /blog
url: "https://fosterbrereton.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: phostershop
github_username:  fosterbrereton

# Build settings
markdown: kramdown
remote_theme: adobe/hyde-theme@v1.0.0
adobe_hyde:
    header_image: stlab-logo-long.svg

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
